---
version: 2.1

orbs:
  orb-tools: twdps/orb-tools@0.1.1

dev-release-filter: &dev-release-filter
  branches:
    only: /main/
  tags:
    ignore: /.*/

edit-tag-publish-filter: &edit-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^edit.*/

patch-tag-publish-filter: &patch-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^patch.*/

minor-tag-publish-filter: &minor-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^minor.*/

major-tag-publish-filter: &major-tag-publish-filter
  branches:
    ignore: /.*/
  tags:
    only: /^major.*/


workflows:
  version: 2

  dev-release-orb-honeycomb-buildevents:
    jobs:
      - orb-tools/validate:
          filters: *dev-release-filter

      - orb-tools/publish-dev:
          context: twdps-orb-authors
          orb-name: twdps/honeycomb-buildevents
          filters: *dev-release-filter
          requires:
            - orb-tools/validate

      - approve-release:
          type: approval
          requires:
            - orb-tools/publish-dev
          filters: *dev-release-filter

      - orb-tools/release-tag:
          context: twdps-orb-authors
          ssh-fingerprints: $SVC_FINGERPRINT
          use-git-diff: false
          static-release-type: minor
          filters: *dev-release-filter
          requires:
            - approve-release

  promote-orb-onepassword:
    jobs:
      # patch, minor, or major publishing, depending on which orb source
      # files have been modified (that logic lives in the
      # release-tag job's source)
      - orb-tools/promote-dev-to-prod:
          name: patch-release
          context: twdps-orb-authors
          release: patch
          orb-name: twdps/honeycomb-buildevents
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *patch-tag-publish-filter

      - orb-tools/promote-dev-to-prod:
          name: minor-release
          context: twdps-orb-authors
          release: minor
          orb-name: twdps/honeycomb-buildevents
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *minor-tag-publish-filter

      - orb-tools/promote-dev-to-prod:
          name: major-release
          context: twdps-orb-authors
          release: major
          orb-name: twdps/honeycomb-buildevents
          ssh-fingerprints: $SVC_FINGERPRINT
          filters: *major-tag-publish-filter

      - orb-tools/documentation-only:
          name: documentation-updates
          filters: *edit-tag-publish-filter
